import Head from "next/head";
import Image from "next/image";

export default function Home() {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <header className="flex justify-between bg-gray-100 items-center">
        <h1 className="p-4">Off the Rook</h1>
        <nav>
          <a href="#">Pieces</a>
          <a href="#">Openings</a>
          <a href="#">Players</a>
          <a href="#">Learn Chess →</a>
        </nav>
      </header>

      <main className="container mx-auto my-6 bg-green-100">
        <h1>Chess openings</h1>
      </main>
    </div>
  );
}
